spring:
  application:
    name: personal-task

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

app:
  jwtSecret: YourSuperSecretKeyThatIsAtLeast32CharsLong!
  jwtExpirationMs: 86400000
