spring:
  application:
    name: personal-task
  mvc:
    cors: 
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  servlet:
    session:
      cookie:
        # Allow the browser to send the cookie in cross-site requests
        same-site: None
        # In dev (HTTP), keep it false; in prod (HTTPS) you should set this true
        secure: false
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

app:
  jwtSecret: YourSuperSecretKeyThatIsAtLeast32CharsLong!
  jwtExpirationMs: 86400000
